#!/usr/bin/env python
import sys 
import time

s1 = sys.platform
current_time = time.clock
unix_time = time.time
#timeReceived = unix_time()
timeReceived = time.time()
print current_time()
print timeReceived

print s1

import sys
import os

s1 = 'a'

t1 = ord(s1)

s1 = 'abc'
t1 = ord(s1)
print t1
a = 10
b = 50

c = a & b

print c
